name: LowellPorter
favicon: null
layout_spectrum: 0.991182676050812
typography_spectrum: 0.9300898057408631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7054685493931174
  lightness: 0.12250634375959635
  saturation: 0.5945897556375712
  rhythmicContrast: 0.9632203057408333
purpose: []
